apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
type: Opaque
data: # Encoded in base64
  postgres-user: Y2F0YWxvZ1Bvc1VzZXI=  # catalogPosUser
  postgres-password: Y2F0YWxvZ1Bvc1Bhc3M=  # catalogPosPass